cachly:
  paths:
    ifpresent-process-definitions:
      storage: my-cache
      serializer: kryo
    process-definitions:
      storage: my-cache
      serializer: kryo
    load-timestamp:
      storage: my-cache
      serializer: kryo
    map:
      storage: my-cache
      serializer: kryo
    users:
      storage: my-cache
      serializer: kryo
    this:
      storage: my-cache
      serializer: kryo
    actual:
      storage: my-cache
      serializer: kryo
  ehcache:
    my-cache:
      serializer: true
      disk:
        persist: true
ehcache:
  storage-path: "data"
  caches:
    my-cache:
      enabled: true
      value-type: com.diamondq.cachly.micronaut.ValueName
      disk:
        max-size: 10Mb
